[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

solc = "0.8.24"
evm_version = "paris"
use_literal_content = true

optimizer = true
optimizer_runs = 200_000

[fmt]
tab_width = 2
line_length = 120
quote_style = "double"
number_underscore = "thousands"

[etherscan]
# testnet
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
tbsc = { key = "${BSCSCAN_KEY}", url = "https://api-testnet.bscscan.com/api" }
fuji = { key = "${SNOWTRACE_KEY}", url = "https://api-testnet.snowtrace.io/api" }
mumbai = { key = "${POLYGONSCAN_KEY}", url = "https://api-testnet.polygonscan.com/api" }
tarb = { key = "${ARBISCAN_KEY}", url = "https://api-goerli.arbiscan.io/api" }
# mainnet
ethereum = { key = "${ETHERSCAN_KEY}" }
bsc = { key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api" }
avalanche = { key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api" }
polygon = { key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api" }
arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }

[rpc_endpoints]
# testnet rpc endpoints
goerli = "${RPC_URL_GOERLI}"
tbsc = "${RPC_URL_TBSC}"
fuji = "${RPC_URL_FUJI}"
mumbai = "${RPC_URL_MUMBAI}"
tarb = "${RPC_URL_TARB}"
# mainnet rpc endpoints
ethereum = "${RPC_URL_ETHER}"
bsc = "${RPC_URL_BSC}"
avalanche = "${RPC_URL_AVALANCHE}"
polygon = "${RPC_URL_POLYGON}"
arbitrum = "${RPC_URL_ARBITRUM}"
